apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapprc
spec:
  replicas: 2
  selector:
    app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebapp
        image: petergillhmg/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080
